-- 0037_suggestions.sql
-- Cut over Member Suggestions (+ their attachments) from Google Sheets to Postgres:
-- MemberSuggestions + MemberSuggestionsAttachments sheets -> two tables here.
--
-- suggestion_id/attachment_id are kept as the existing human-readable business keys
-- (YYYY-NNN / ATT-NNNNNN, generated by a per-prefix max+1 counter, same as
-- competitions' match_id and 200 Club/renewals precedent) rather than replaced by a
-- uuid — nothing about the generation scheme needs to change.
--
-- committee_only/committee_acceptance were free-text 'Y'/'' sentinels in the sheet —
-- real booleans here; the data layer maps back to 'Y'/'' on read so the API/frontend
-- contract (MemberSuggestion.committeeOnly/committeeAcceptance, both typed as string)
-- doesn't need to change.
--
-- dateReceived/targetCompletionDate/reviewDate/dateCompleted are always set via native
-- <input type="date"> (ISO yyyy-mm-dd) client-side, so real `date` columns here.

create table if not exists suggestions (
  suggestion_id              text primary key,
  title                      text not null,
  category                   text not null default 'Other'
                               check (category in ('Facilities', 'Green', 'Grounds', 'Clubhouse', 'Bar', 'Social', 'Finance', 'Other')),
  description                text not null,
  reason_for_improvement     text not null,
  created_by_username        text not null references users(username),
  created_at                 timestamptz not null default now(),

  committee_only             boolean not null default false,
  date_received               date,
  committee_acceptance       boolean not null default false,
  committee_acceptance_reason text,
  priority                   text check (priority in ('Low', 'Medium', 'High', 'Safety essential')),
  coordinator_username       text references users(username),
  estimated_cost             numeric(10,2),
  funding_source             text check (funding_source in ('Club Funds', 'Grant', 'Fundraising', 'Sponsor', 'Other')),
  cost_quotes_details        text,
  decision                   text check (decision in ('Approved', 'Not Approved', 'Deferred')),
  decision_reason            text,
  target_completion_date     date,
  progress_notes             text,
  review_date                date,
  final_outcome              text check (final_outcome in ('Completed', 'Cancelled', 'On Hold')),
  date_completed              date,

  updated_at                 timestamptz,
  updated_by_username        text references users(username)
);

create table if not exists suggestion_attachments (
  attachment_id      text primary key,
  suggestion_id       text not null references suggestions(suggestion_id) on delete cascade,
  type                text not null check (type in ('link', 'image', 'document')),
  drive_file_id        text,
  url                 text not null,
  description         text not null,
  file_name            text,
  mime_type            text,
  file_size            bigint,
  display_order        int not null default 0,
  added_at             timestamptz not null default now(),
  added_by_username    text not null references users(username),
  is_deleted           boolean not null default false
);

create index if not exists suggestion_attachments_suggestion_id_idx on suggestion_attachments (suggestion_id);

alter table suggestions enable row level security;
alter table suggestion_attachments enable row level security;
